git clone git@github.com:datarobot/adipose.git
git clone git@github.com:datarobot/cicada.git
git clone git@github.com:datarobot/coding-interview-questions.git
git clone git@github.com:datarobot/custom-task-stackbot.git
git clone git@github.com:datarobot/datarobot-user-models.git
git clone git@github.com:datarobot/data-science-scripts.git
git clone git@github.com:datarobot/dr-usertool.git
git clone git@github.com:datarobot/jenkins-jobs.git
git clone git@github.com:datarobot/mldev-observability.git
git clone git@github.com:datarobot/mldev-scripts.git
git clone git@github.com:datarobot/mlops_infrastructure.git
git clone git@github.com:datarobot/mlops-scripts.git
git clone git@github.com:datarobot/public_api_client.git
git clone git@github.com:datarobot/stackbot.git
